name: dft3c-gpu
channels:
  - conda-forge
dependencies:
  - ase
  - dftd3-python
  - dftd4-python
  - pyscf >=2.8,<2.14
  - python
  - pytorch * cuda*
  - skala
  - cuda-toolkit >=12,<13
  - cuda-version >=12,<13
  - cutensor >=2
  # Testing and development
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-randomly
  - ruff
  - mypy
  - pip:
    - gpu4pyscf-cuda12x >=1.5,<1.8
